# This program says hello and asks for name
print("Hello world !")
print("What is your name ?")
myName = input()
print("It is good to meet you, " + myName)
print("Lenght of your name is :")
print(len(myName))
print("What is your age ?")
age = input()
print("You will be " + str(int(age) + 1) + " in a year.")
